export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PAGE_ERROR = "SET_PAGE_ERROR";
export const SET_LOADING = "SET_LOADING";
export const GET_CLASSES = "GET_CLASSES";
export const ADD_CLASS = "ADD_CLASS";
export const REMOVE_CLASS = "REMOVE_CLASS";
export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";